package web.app.accounts;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class DBcontroller {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EmployeeRepository employeeRepository;

    @PostMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestBody Employee employee) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
//
//        Employee n = new Employee();
//        n.setFirstName(firstName);
//        n.setSurname(surname);
//        n.setAccountNumber(accountNumber);
        employeeRepository.save(employee);
        return "Saved";
    }

    @DeleteMapping(path="/delete")
    public @ResponseBody String deleteUser(@RequestBody Employee employee){
        employeeRepository.delete(employee);
        return "deleted";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Employee> getAllUsers() {
        // This returns a JSON or XML with the users
        return employeeRepository.findAll();
    }
}
